### ISSUE TITLE
sourmash scripts pairwise missing

### ISSUE THREAD

**Issue by betsyalf** [sourmash-bio/sourmash_plugin_betterplot#58]
Not sure if I should be posting in Sourmash or betterplot.  Im working my way through betterplot markdown page https://github.com/sourmash-bio/sourmash_plugin_betterplot

"""
# build pairwise
sourmash sig cat sketches/{2,47,48,49,51,52,53,59,60,63}.sig.zip \
    -o 10sketches.sig.zip
sourmash scripts pairwise 10sketches.sig.zip -o 10sketches.pairwise.csv

# convert pairwise
sourmash scripts pairwise_to_matrix 10sketches.pairwise.csv \
    -o 10sketches.pairwise.cmp \
    --labels-to 10sketches.pairwise.cmp.labels_to.csv
    
# plot!
sourmash scripts plot2 10sketches.pairwise.cmp \
    10sketches.pairwise.cmp.labels_to.csv \
    -o plot2.pairwise.10sketches.cmp.png
"""

When I get to the below command, I get an error that pairwise isnt an option: 
sourmash scripts pairwise 10sketches.sig.zip -o 10sketches.pairwise.csv

Error:
 scripts: error: argument subcmd: invalid choice: 'pairwise' (choose from 'cluster_to_categories', 'clustermap1', 'mds2', 'mds', 'pairwise_to_matrix', 'plot2', 'plot3', 'presence_filter', 'tsne2', 'tsne', 'upset', 'venn')

When I look in [sourmash_plugin_betterplot.py](https://github.com/sourmashbio/sourmash_plugin_betterplot/blob/main/src/sourmash_plugin_betterplot.py), many of the classes such as "cluster_to_categories" reference "pairwise_csv"

**Comment by ctb** [comment]
Either issue tracker works!

`sourmash scripts pairwise` is part of the [`sourmash_plugin_branchwater`](https://github.com/sourmash-bio/sourmash_plugin_branchwater) package. So you'll want to `conda install` that as well. I'll update the docs to make that clear - thanks!

**Comment by betsyalf** [comment]
Thanks Titus.  It worked...beautifully.

I'm going to be explicit in the solution in case someone finds this in the future:  To construct the pairwise analysis and visualizations, Sourmash, sourmash_plugin_branchwater, and sourmash_plugin_betterplot need to be installed.
